import { Inter } from "next/font/google";


import "./globals.css";

import Header from "@/components/Header";
import ImageDiary from "@/components/ImageDiary";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <h2 className="font-bold m-6 text-[1.2em]"
        >A nasa dispoem de sua informações, e nos mastigamos para vc</h2>
        <ImageDiary />
        {children}
        </body>
    </html>
  );
}
